# Generated by Django 5.2.1 on 2025-05-14 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosSubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_min_lote', models.FloatField(blank=True, null=True)),
                ('area_max_lote', models.FloatField(blank=True, null=True)),
                ('frente_min_lote', models.FloatField(blank=True, null=True)),
                ('algoritmo_seleccionado', models.CharField(blank=True, max_length=100, null=True)),
                ('otros_criterios_json', models.JSONField(blank=True, help_text='Otros criterios urbanísticos en JSON', null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_subdivision', to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_terreno', models.CharField(max_length=255)),
                ('geometria_geojson', models.TextField(help_text='Geometría del terreno en formato GeoJSON')),
                ('area_total', models.FloatField(blank=True, help_text='Área total calculada del terreno', null=True)),
                ('metadatos_json', models.JSONField(blank=True, help_text='Metadatos adicionales en formato JSON', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrenos', to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='LoteResultante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50)),
                ('geometria_lote_geojson', models.TextField(help_text='Geometría del lote en formato GeoJSON')),
                ('area_lote', models.FloatField(blank=True, null=True)),
                ('frente_lote', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('terreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_resultantes', to='core.terreno')),
            ],
        ),
    ]
